### **ARRAY**

In [1]:
import numpy as np

In [2]:
new_array = np.array([23,45,78])
print(new_array)

[23 45 78]


In [3]:
#CREATING AN ARRAY
import numpy as np
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
new_array_1 = np.array([12,23,"buddhist record of the western world"])
new_array_1
#   ishme array ne sabi ko ek data type m convert kr diya isse ye pta chlta h ki jb hum array m ek se jyda data type 
#    ko dalte h toh wah use ek hi data type m convet krta h 

array(['12', '23', 'buddhist record of the western world'], dtype='<U36')

In [6]:
print(new_array_1)

['12' '23' 'buddhist record of the western world']


In [7]:
import numpy
a = numpy.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
import numpy as ny
a = ny.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
import numpy as name
a = name.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
name.array((1,2,4,5,6))

array([1, 2, 4, 5, 6])

In [11]:
name.array({1,2,4,5,6})

array({1, 2, 4, 5, 6}, dtype=object)

In [12]:
array2 = name.array([12,23,"if the plan doesn't work chnage the plan but never the goal",
                    "buddist record of the western world"])
array2

array(['12', '23',
       "if the plan doesn't work chnage the plan but never the goal",
       'buddist record of the western world'], dtype='<U59')

In [13]:
len("if the plan doesn't work chnage the plan but never the goal")

59

## **RESTRICTIONS OF ARRAY**

- ALL ELEMENT OF THE ARRAY MUST BE OF THE SAME TYPE OF DATA
- ONCE CREATED , THE TOTAL SIXE OF THE ARRAY CAN'T CHANGE

### **WE CAN ACCES AN INDIVISUAL ELEMENT OF THE ARRAY  AS WE WOULD ACCESS AN ELEMENT IN THIS ORIGINAL LIST  USING THE INTERGER  INDEX OF THE ELEMENT WITHIN SQUARE BRACKET**

In [ ]:
# the arary is mutable

In [17]:
import numpy as np
a = np.array([1,2,3,4,5,6,"if the plan doesn't work chnage the plan but never the goal"])


In [18]:
a[0]

'1'

In [19]:
a[4]

'5'

In [20]:
a[6]

"if the plan doesn't work chnage the plan but never the goal"

In [23]:
a[6] = 4


In [26]:
print(a)

['1' '2' '3' '4' '5' '6' '4']


### **ARRAY ARE MUTABLE**

In [6]:
# array is mutable 
a[0] = 13
a

array(['13', '2', '3', '4', '5', '6',
       "if the plan doesn't work chnage the plan but never the goal"],
      dtype='<U59')

In [7]:
a[3] = 0
print(a)

['13' '2' '3' '0' '5' '6'
 "if the plan doesn't work chnage the plan but never the goal"]


#### **ANOTHER DIFFERENCE BETWEEN AN ARRAY AND A  LIST IS THAT AN ELEMENT IF THE ARRAY CAN BE ACCESSED BY SPECIFYING THE INIDEX ALONG EACH AXIS WITHIIN A SINGLE SET OF SQUARE BRACKET SEPERATE BY COMMAS**

In [3]:
two_dimen_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(two_dimen_array)
two_dimen_array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
# we want to first row
two_dimen_array[0]

array([1, 2, 3, 4])

In [5]:
# we want to second row

two_dimen_array[1]

array([5, 6, 7, 8])

In [6]:
# we want to third row

two_dimen_array[2]

array([ 9, 10, 11, 12])

In [7]:
# we want to first column

two_dimen_array[:,0]

array([1, 5, 9])

In [10]:

# we want to second column
two_dimen_array[:,1]

array([ 2,  6, 10])

In [11]:
# we want to third column

two_dimen_array[:,2]

array([ 3,  7, 11])

## **ARRAY ATTRIBUTES**
**ndim** : The number of dimension of an array is contained in the ndim attribute

In [12]:
array = np.array(12)
array.ndim # ye btata h ki table kons e dimension ki h 

0

In [14]:
array_1 = np.array([1,2,3,4,5])
array_1.ndim

1

In [18]:
array_2 = np.array([[1,2,3,4],[5,6,7,8]])
array_2.ndim

2

## **SHAPE**  :: 
 The shape of any array is a tuple of non-negative integers that specify the number of elemnet along each dimension

In [21]:
x = np.array([[1,2,3],[4,5,6]])
print(x)



print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### **SIZE** : 
THE FIXED TOTAL NUMBER OF ELEMENT IN ARRAY IS CONTAINED IN THE SIZE ATTRIBUTE

In [24]:
table = np.array([[2,4,6,8,10], [12,14,16,18,20]])
print(table.size) # ye batata h ki table m total kitne elemnt h 
print(table.shape) # ye btata h ki table m kitne row or kitne column h

10
(2, 5)


## **dtype** : 
The data type of the element of the array can be checked using the dtype attribute.

***note*** :
the data type of all the element of numpy array is same . i.e.  homogneious

In [25]:
table.dtype

dtype('int32')

In [30]:
table_1 = np.array([['neeraj', 34,34], [True, False, 4.5]])
print(table_1)
table_1.dtype # ye btata h ki element kon se data type ke h array ke aander

[['neeraj' '34' '34']
 ['True' 'False' '4.5']]


dtype('<U32')

# **SOME OTHER TECHNIQUE TO CREATE AN ARRAY**
THE SECTION COVER  ***np.zeros(),np.one() , np.empty(), np.arange(), np.linspace()***

**np.zeros**

In [3]:
zero_array = np.zeros(6)
print(zero_array)

[0. 0. 0. 0. 0. 0.]


In [6]:
zero_array = np.zeros((2,2))
print(zero_array)

[[0. 0.]
 [0. 0.]]


In [37]:
print(type(zero_array))
print(zero_array.size)
print(zero_array.shape)

<class 'numpy.ndarray'>
6
(6,)


In [1]:
# create a tuple of zero(2 rows and 3 colum)
zero_array_table = np.zeros((2,3))
print(zero_array_table)

NameError: name 'np' is not defined

**np.one** : you can create an array filled with 1


In [41]:
one_array = np.ones((3,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## ***np.empty*** :
this create an empty array . the element of an empty aray are random an depend on the side of the memory . the reason to use empty over zeroes is speed -- just make sure to fill every element afterwards

In [47]:
empty_array = np.empty(7)
empty_array

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.34599605e-307,
       1.89146896e-307, 7.56571288e-307, 3.14082867e-317])

## **np.arange(start ,stop ,step)**  :
CREATE AN ARRAY WITHIN A RANGE

In [45]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [46]:
y = np.arange(1,9,2)
print(y)

[1 3 5 7]


## **np.linspace(start,stop, step)** : 
CREATE AN ARRAY WITH THE VALUE THAT ARE SPACE LINEARLY IN A SPECIFIC INTERVAL

In [33]:
new_array =  np.linspace(1,10,3)
new_array

array([ 1. ,  5.5, 10. ])

## CONCATANATION AND SORTING OF ARRAY 


 ## **np.sort()**

In [ ]:
array = np.array([1,6,4,2,7,8,0,9])
array_sorted = np.sort(array) # ye krne ke baad array change ni hoga jab hum array ko pritn karnege to whi printi krega
array_sorted

array

In [8]:
# array ko change krne ke liyee ye krna padega
arr = np.sort([1,6,4,2,7,8,0,9])
arr

array([0, 1, 2, 4, 6, 7, 8, 9])

array([0, 1, 2, 4, 6, 7, 8, 9])

## **CONCATINATION OF ARRAY**

In [9]:
array_1 = np.array([1,2,6,3,8])
array_2 = np.array([3,4,5,9,8])
array_1 + array_2 # concatinate ni hora

array([ 4,  6, 11, 12, 16])

## **np.concatenate()** : ish method se ye concatinate hoga

In [18]:
array_concatinate = np.concatenate([array_1,array_2])
array_concatinate


array([1, 2, 6, 3, 8, 3, 4, 5, 9, 8])

In [22]:
array_concatination = np.concatenate([array_2,array_1])
array_concatination

array([3, 4, 5, 9, 8, 1, 2, 6, 3, 8])

 ## concatinate 2d array

In [23]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[8,9]])
print("x\n",a)
print("y\n",b)

x
 [[1 2]
 [3 4]]
y
 [[5 6]
 [8 9]]


 ## **CONCATINATE ALONG X AXIS**

In [27]:
# conacatinate along x - axis = 0
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

 ## **CONCATINATE ALONG  Y AXIS**


In [32]:
 # concatinate along y - axis = 1
np.concatenate((a,b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 8, 9]])

In [34]:
axis = 0 direction (down),(row)
|
|
|
|
↓

SyntaxError: invalid character '↓' (U+2193) (3572278233.py, line 3)

axis = 1 direction (across), (column)
--------→ → →

## **Reshape the array**

## **arr.reshape**
using arr.reshape will give a new shape to an array without changing the data just rememmber that when you us ethe 
reshapwmethod the array you eant to produce needs to have the same number of element as the original array if you
start with an array with 12 element  you will need to make sure that your array also have  a total of 12 element 

In [ ]:
import numpy as np 


In [38]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [40]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [41]:
a

array([0, 1, 2, 3, 4, 5])

In [44]:
c = b.reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

## **INDEXING USING CONDITION IN ARRAY**

In [28]:
list1 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
list1

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [29]:
list1 < 5

TypeError: '<' not supported between instances of 'list' and 'int'

In [30]:
list1(list1 < 5)

TypeError: '<' not supported between instances of 'list' and 'int'

In [31]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [33]:
a[a<5]

array([1, 2, 3, 4])

In [34]:
# you can select even number 
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [36]:
c = a[(a>2) & (a<11)] # you can't use and use this "&"
c
print(c.ndim)

1


In [63]:
d = a[(a>5) | (a==2)]
d

array([ 2,  6,  7,  8,  9, 10, 11, 12])

## **BASIC ARRAY OPERATION**
- THIS SECITON COVER ADDITION SUBTRACTION MULTIPLACTION AND DIVISION AND MORE

In [1]:
import numpy as np 


In [2]:
# we can add array togather wtih the + sign() 
data = np.array([1,2,3])
data1 = np.array([4,5,6])
data + data1

array([5, 7, 9])

In [5]:
# subtraction
print(data - data1)
# multiplaction
print(data * data1)
# division
print(data / data1)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## **.sum()** 
- SUM ALL THE ELEMENT IN ARRAY 

In [6]:
a = np.array([1,2,3,4,5,6])
a.sum()

21

In [7]:
# sum in 2 dimensional
b = np.array([[1,1],[2,2]])
b.sum(axis = 0)

array([3, 3])

In [8]:
b.sum(axis = 1)

array([2, 4])

## **BROADCASTING**
- BROADCASTING IS A MECHANISM THAT ALLOWS NUMPY TO PERFORM OPERATION ON ARRAY  OF DIFFERNET SHAPE.
- THERE ARE MANY BROADCASTING RULEES WHICH YOU CAN LEARN FROM THE NUMPY DOCUMENTATION

In [9]:
distance_in_km = np.array([5,2,7,3]) # shape : (4,)  dimension = 1
single_value = np.array(1000) # shape : ()  , dimension: 0
distance_in_km * single_value

array([5000, 2000, 7000, 3000])

In [10]:
print(distance_in_km.shape)
print(single_value.shape)

(4,)
()


In [12]:
print(distance_in_km.ndim)
print(single_value.ndim)

1
0
